name: Auto Increment Tag

on:
  push:
    branches:
      - main

jobs:
  increment-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Get latest tag and calculate new tag
        id: tag
        run: |
          # Get the latest tag sorted in descending order (by version)
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest_tag"
          
          # If no tag exists, start from 1; otherwise, strip non-numeric prefix and increment the numeric portion
          if [ -z "$latest_tag" ]; then
            new_tag="1"
          else
            num=$(echo "$latest_tag" | sed 's/^[^0-9]*//')
            new_tag=$((num + 1))
          fi
          echo "New tag: $new_tag"
          echo "::set-output name=new_tag::$new_tag"

      - name: Create and push new tag
        run: |
          new_tag=${{ steps.tag.outputs.new_tag }}
          git tag "$new_tag"
          git push origin "$new_tag"
