name: Auto Release Tag NoPing

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push new tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          new_version="v$(echo $latest_tag | awk -F. -v OFS=. '{$NF++;print}')"
          git tag $new_version
          git push origin $new_version